pipeline {
    agent any
    stages {
        stage('Build Python App') {
            steps {
                sh 'docker build -t python-flask-app .'
            }
        }
        stage('Run App') {
            steps {
                sh 'docker run -d -p 5000:5000 --name flask-container python-flask-app'
            }
        }
    }
}
